org: flxamartinez
service: api-alumnos

provider:
  name: aws
  runtime: python3.13
  timeout: 30
  iam:
    role: arn:aws:iam::609896966514:role/LabRole

functions:
  crear:
    handler: CrearAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/crear
          method: post
          cors: true
          integration: lambda

  listar:
    handler: ListarAlumnos.lambda_handler
    events:
      - http:
          path: /alumnos/listar
          method: post
          cors: true
          integration: lambda

  modificar:
    handler: ModificarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/modificar
          method: patch
          cors: true
          integration: lambda

  buscar:
    handler: BuscarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/buscar
          method: post
          cors: true
          integration: lambda

  eliminar:
    handler: EliminarAlumno.lambda_handler
    events:
      - http:
          path: /alumnos/eliminar
          method: delete
          cors: true
          integration: lambda
